#!/bin/sh

pdflatex sourcemem-online -interaction=batchmode > /dev/null && pdflatex sourcemem-online -interaction=batchmode > /dev/null && biblatex sourcemem-online && pdflatex sourcemem-online -interaction=batchmode > /dev/null && pdflatex sourcemem-online -interaction=batchmode > /dev/null
